"""
Pydantic Models - Full Stack Alignment
======================================
Strict Pydantic models matching MongoDB $jsonSchema validators.

RULES:
- All fields use camelCase (SSOT)
- No system fields in Create models (generated by backend)
- Explicit type conversions (ObjectId, Date, int, bool)
- additionalProperties: false equivalent via model_config

Collections:
1. categories
2. category_requests
3. inquiries
4. inquiry_reports
5. product_requests
6. products
7. seller_listings
8. spec_templates
9. subscription_changes
10. subscriptions
11. users
"""

from pydantic import BaseModel, Field, field_validator, model_validator, ConfigDict
from typing import Optional, List, Dict, Any, Literal
from datetime import datetime
from enum import Enum
from bson import ObjectId


# ================== ENUMS ==================

class AccountStatus(str, Enum):
    ACTIVE = "active"
    DELETED = "deleted"
    ARCHIVED = "archived"
    SUSPENDED = "suspended"

class SubscriptionPlan(str, Enum):
    FREE = "free"
    STANDARD = "standard"
    PRO = "pro"
    ENTERPRISE = "enterprise"

class SubscriptionStatus(str, Enum):
    ACTIVE = "active"
    EXPIRED = "expired"
    CANCELLED = "cancelled"

class ListingStatus(str, Enum):
    DRAFT = "draft"
    ACTIVE = "active"
    PAUSED = "paused"
    ARCHIVED = "archived"
    DELETED = "deleted"

class InquiryStatus(str, Enum):
    PENDING = "pending"
    VIEWED = "viewed"
    QUOTED = "quoted"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    EXPIRED = "expired"
    CANCELLED = "cancelled"

class ReportType(str, Enum):
    SPAM = "spam"
    FRAUD = "fraud"
    PRICING_ISSUE = "pricing_issue"
    INAPPROPRIATE = "inappropriate"

class ReportStatus(str, Enum):
    OPEN = "open"
    UNDER_REVIEW = "under_review"
    RESOLVED = "resolved"
    REJECTED = "rejected"

class RequestStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"

class SubscriptionAction(str, Enum):
    ACTIVATE = "activate"
    UPGRADE = "upgrade"
    DOWNGRADE = "downgrade"
    EXPIRE = "expire"
    CANCEL = "cancel"

class SpecFieldType(str, Enum):
    TEXT = "text"
    NUMBER = "number"
    DROPDOWN = "dropdown"
    BOOLEAN = "boolean"


# ================== BASE CONFIGS ==================

class StrictModel(BaseModel):
    """Base model with strict validation - rejects extra fields"""
    model_config = ConfigDict(
        extra='forbid',  # Reject extra fields (like additionalProperties: false)
        str_strip_whitespace=True,
        validate_assignment=True
    )


# ================== 1. CATEGORIES ==================

class CategorySettings(BaseModel):
    """Category settings object"""
    allowedUnits: Optional[List[str]] = []
    defaultUnit: Optional[str] = None
    allowedSellerTypes: Optional[List[str]] = []
    dimensionsEnabled: Optional[bool] = False
    dimensionUnits: Optional[List[str]] = []
    dimensionFormat: Optional[str] = None
    dropdownOverrides: Optional[Dict[str, Any]] = None

class CategoryCreate(StrictModel):
    """
    Create category (admin only).
    System fields auto-generated: createdAt, updatedAt, createdBy
    """
    name: str = Field(..., min_length=1, max_length=200)
    description: Optional[str] = None
    imageUrl: Optional[str] = None  # Firebase URL
    icon: Optional[str] = None
    displayOrder: int = Field(default=0, ge=0)
    settings: Optional[CategorySettings] = None
    isActive: bool = True

class CategoryUpdate(StrictModel):
    """Update category (admin only)"""
    name: Optional[str] = Field(None, min_length=1, max_length=200)
    description: Optional[str] = None
    imageUrl: Optional[str] = None
    icon: Optional[str] = None
    displayOrder: Optional[int] = Field(None, ge=0)
    settings: Optional[CategorySettings] = None
    isActive: Optional[bool] = None


# ================== 2. CATEGORY REQUESTS ==================

class CategoryRequestCreate(StrictModel):
    """
    Request new category (seller).
    System fields auto-generated: requestedBy, requestedByEmail, status, createdAt, updatedAt
    """
    categoryName: str = Field(..., min_length=2, max_length=200)
    description: Optional[str] = None
    reason: Optional[str] = None

class CategoryRequestReview(StrictModel):
    """Admin review of category request"""
    status: RequestStatus
    adminNotes: Optional[str] = None


# ================== 3. INQUIRIES ==================

class BuyerInfo(BaseModel):
    """Buyer information embedded in inquiry"""
    name: str
    companyName: Optional[str] = None
    email: str
    phone: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None

class Quote(BaseModel):
    """Seller quote for inquiry"""
    price: Optional[float] = None
    moq: Optional[int] = None
    leadTimeDays: Optional[int] = None
    validTill: Optional[datetime] = None
    sellerNote: Optional[str] = None
    quotedAt: Optional[datetime] = None

class InquiryCreate(StrictModel):
    """
    Create inquiry (buyer).
    System fields auto-generated: buyerId, sellerId (from listing), status, createdAt, updatedAt
    """
    listingId: str = Field(..., description="Listing ObjectId as string")
    quantity: int = Field(..., gt=0)
    message: Optional[str] = None
    requirementNote: Optional[str] = None
    buyerType: str = Field(default="buyer")
    buyerInfo: BuyerInfo

class InquiryQuote(StrictModel):
    """Seller quote submission"""
    price: float = Field(..., gt=0)
    moq: int = Field(..., gt=0)
    leadTimeDays: int = Field(..., ge=1)
    validTill: datetime
    sellerNote: Optional[str] = None


# ================== 4. INQUIRY REPORTS ==================

class InquiryReportCreate(StrictModel):
    """
    Report an inquiry.
    System fields auto-generated: sellerId, buyerId (from inquiry), status, createdAt
    """
    inquiryId: str = Field(..., description="Inquiry ObjectId as string")
    reportType: ReportType
    details: Optional[str] = None

class InquiryReportReview(StrictModel):
    """Admin review of inquiry report"""
    status: ReportStatus


# ================== 5. PRODUCT REQUESTS ==================

class ProductRequestCreate(StrictModel):
    """
    Request new product (seller).
    System fields auto-generated: requestedBy, requestedByEmail, status, createdAt, updatedAt
    """
    productName: str = Field(..., min_length=2, max_length=200)
    suggestedCategoryId: str = Field(..., description="Category ObjectId as string")
    categoryName: Optional[str] = None
    manufacturerId: Optional[str] = None
    description: Optional[str] = None
    baseSpecifications: Optional[Dict[str, Any]] = {}
    reason: Optional[str] = None

class ProductRequestReview(StrictModel):
    """Admin review of product request"""
    status: RequestStatus
    adminNotes: Optional[str] = None


# ================== 6. PRODUCTS ==================

class ProductCreate(StrictModel):
    """
    Create product (admin only).
    Products are TEMPLATES - no pricing.
    System fields auto-generated: categoryName (lookup), createdAt, updatedAt, createdBy, isActive
    """
    name: str = Field(..., min_length=2, max_length=200)
    categoryId: str = Field(..., description="Category ObjectId as string")
    description: Optional[str] = Field(None, max_length=2000)
    family: Optional[str] = Field(None, max_length=100)
    variant: Optional[str] = Field(None, max_length=100)
    coverImageUrl: Optional[str] = None  # Firebase URL
    specTemplateIds: List[str] = Field(default_factory=list)
    unit: Optional[str] = Field(None, max_length=20)

class ProductUpdate(StrictModel):
    """Update product (admin only)"""
    name: Optional[str] = Field(None, min_length=2, max_length=200)
    description: Optional[str] = None
    family: Optional[str] = None
    variant: Optional[str] = None
    coverImageUrl: Optional[str] = None
    specTemplateIds: Optional[List[str]] = None
    unit: Optional[str] = None
    isActive: Optional[bool] = None


# ================== 7. SELLER LISTINGS ==================

class ProductSnapshot(BaseModel):
    """Snapshot of product at listing creation time"""
    name: str
    categoryId: str  # Will be converted to ObjectId
    categoryName: str
    coverImageUrl: Optional[str] = None

class Availability(BaseModel):
    """Stock and availability info"""
    moq: int = Field(..., ge=1)
    stock: int = Field(default=0, ge=0)
    leadTimeDays: int = Field(default=1, ge=1)
    stockStatus: str = Field(default="in_stock")

class PricingSlab(BaseModel):
    """Price tier for quantity-based pricing"""
    quantityMin: int = Field(..., ge=1)
    quantityMax: Optional[int] = None  # null for "and above"
    pricePerUnit: float = Field(..., gt=0)
    currency: str = Field(default="INR")
    
    @model_validator(mode='after')
    def validate_quantity_range(self):
        if self.quantityMax is not None and self.quantityMin >= self.quantityMax:
            raise ValueError("quantityMin must be less than quantityMax")
        return self

class Pricing(BaseModel):
    """Pricing configuration"""
    pricingType: str = Field(default="slab")  # "slab" or "fixed"
    slabs: List[PricingSlab] = Field(..., min_length=1)

class ListingCreate(StrictModel):
    """
    Create listing (seller).
    System fields auto-generated: sellerId (from token), productSnapshot (lookup), createdAt, updatedAt
    """
    productId: str = Field(..., description="Product ObjectId as string")
    sellerType: str = Field(..., description="Manufacturer, Dealer, Distributor, Trader")
    specifications: Optional[Dict[str, Any]] = {}
    specTemplateIds: Optional[List[str]] = []
    specTemplateVersions: Optional[List[int]] = []
    availability: Availability
    pricing: Pricing
    images: List[str] = Field(..., min_length=1, description="Firebase URLs")
    status: ListingStatus = Field(default=ListingStatus.DRAFT)

class ListingUpdate(StrictModel):
    """Update listing (seller)"""
    sellerType: Optional[str] = None
    specifications: Optional[Dict[str, Any]] = None
    availability: Optional[Availability] = None
    pricing: Optional[Pricing] = None
    images: Optional[List[str]] = None
    status: Optional[ListingStatus] = None


# ================== 8. SPEC TEMPLATES ==================

class SpecField(BaseModel):
    """Single specification field definition"""
    key: str = Field(..., min_length=1)
    label: str = Field(..., min_length=1)
    fieldType: SpecFieldType
    unit: Optional[str] = None
    options: Optional[List[str]] = []  # For dropdown type
    required: bool = False
    displayOrder: int = Field(..., ge=0)

class SpecTemplateCreate(StrictModel):
    """
    Create spec template (admin only).
    System fields auto-generated: createdAt, updatedAt, createdBy, isActive
    """
    name: str = Field(..., min_length=2, max_length=200)
    categoryId: str = Field(..., description="Category ObjectId as string")
    fields: List[SpecField] = Field(..., min_length=1)

class SpecTemplateUpdate(StrictModel):
    """Update spec template (admin only)"""
    name: Optional[str] = Field(None, min_length=2, max_length=200)
    fields: Optional[List[SpecField]] = None
    isActive: Optional[bool] = None


# ================== 9. SUBSCRIPTION CHANGES ==================

class NewSubscription(BaseModel):
    """Subscription data for change log"""
    planName: SubscriptionPlan
    durationDays: int = Field(..., ge=1)
    startDate: datetime
    endDate: Optional[datetime] = None
    status: SubscriptionStatus
    lastUpdatedBy: Optional[str] = None  # String or ObjectId
    updatedAt: datetime
    notes: Optional[str] = None
    createdAt: datetime

class SubscriptionChangeCreate(StrictModel):
    """
    Log subscription change (admin action).
    System fields auto-generated: adminId, adminEmail (from token), createdAt
    """
    userId: str = Field(..., description="User ObjectId as string")
    action: SubscriptionAction
    oldSubscription: Optional[Dict[str, Any]] = None
    newSubscription: NewSubscription
    note: Optional[str] = None


# ================== 10. SUBSCRIPTIONS ==================

class SubscriptionCreate(StrictModel):
    """
    Create subscription (admin/system).
    System fields auto-generated: createdAt
    """
    userId: str = Field(..., description="User ObjectId as string")
    planName: SubscriptionPlan
    durationDays: int = Field(..., ge=1)
    startDate: datetime
    endDate: Optional[datetime] = None
    status: SubscriptionStatus
    enquiryLimit: int = Field(default=5, ge=0)
    enquiriesUsed: int = Field(default=0, ge=0)
    enquiriesResetAt: Optional[datetime] = None
    notes: Optional[str] = None

class SubscriptionUpdate(StrictModel):
    """Update subscription (admin only)"""
    planName: Optional[SubscriptionPlan] = None
    durationDays: Optional[int] = Field(None, ge=1)
    endDate: Optional[datetime] = None
    status: Optional[SubscriptionStatus] = None
    enquiryLimit: Optional[int] = Field(None, ge=0)
    notes: Optional[str] = None


# ================== 11. USERS ==================

class UserProfile(BaseModel):
    """User profile information"""
    businessName: Optional[str] = None
    phone: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    pincode: Optional[str] = None
    address: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None

class UserGST(BaseModel):
    """GST verification info"""
    number: Optional[str] = None
    status: Optional[str] = None
    verified: bool = False

class UserSubscription(BaseModel):
    """User subscription status"""
    plan: str = Field(default="free")
    status: str = Field(default="active")
    startDate: Optional[datetime] = None
    endDate: Optional[datetime] = None
    trialEndsAt: Optional[datetime] = None
    inquiryLimit: int = Field(default=5, ge=0)
    enquiriesThisMonth: int = Field(default=0, ge=0)
    enquiriesResetAt: Optional[datetime] = None

class UserCreate(StrictModel):
    """
    Create user (registration).
    System fields auto-generated: roles, isAdmin, canLogin, isActive, createdAt, updatedAt
    """
    email: str = Field(..., min_length=5)
    firebaseUid: str = Field(..., min_length=10)
    profile: Optional[UserProfile] = None
    gst: Optional[UserGST] = None
    accountStatus: AccountStatus = Field(default=AccountStatus.ACTIVE)

class UserProfileUpdate(StrictModel):
    """
    Update user profile (self-service).
    CANNOT update: roles, isAdmin, subscription, accountStatus
    """
    profile: Optional[UserProfile] = None
    gst: Optional[UserGST] = None
    recentSearches: Optional[List[str]] = None
    favourites: Optional[List[str]] = None  # Listing ObjectIds as strings

class UserAdminUpdate(StrictModel):
    """
    Update user (admin only).
    CAN update sensitive fields.
    """
    roles: Optional[List[str]] = None
    isAdmin: Optional[bool] = None
    profile: Optional[UserProfile] = None
    gst: Optional[UserGST] = None
    subscription: Optional[UserSubscription] = None
    accountStatus: Optional[AccountStatus] = None
    canLogin: Optional[bool] = None
    isActive: Optional[bool] = None


# ================== RESPONSE MODELS ==================

class PaginatedResponse(BaseModel):
    """Standard paginated response"""
    items: List[Any]
    total: int
    page: int
    pageSize: int
    totalPages: int

class SuccessResponse(BaseModel):
    """Standard success response"""
    message: str
    data: Optional[Any] = None

class ErrorResponse(BaseModel):
    """Standard error response"""
    errorCode: str
    message: str
    field: Optional[str] = None
    details: Optional[Any] = None
